### ISSUE TITLE
Load Reads:

### ISSUE THREAD

**Issue by devarajphukan** [CSCLabTW/ReadStackCorrector#1]
I am not able to get output from the program after " Load Reads : " . Please Help me with the further procedure

**Comment by moneycat** [comment]
Hi,

Cloud you please provide more information about your execution? For example,
1) the parameters  for execution
2) the log files from the 'work' directory you set
3) any error messages prompt on screen

Best

**Comment by rammesessn** [comment]
@moneycat Hi, I am also getting the same thing. No error is coming. this is the output i am getting in the name node and one more thing i am running the hadoop 2.7 .
![2](https://cloud.githubusercontent.com/assets/6651131/13567730/edd4af6c-e482-11e5-8220-b34562934d09.png)

**Comment by devarajphukan** [comment]
Sir, I have run the jar file in your repo with hadoop 2.7 and dataset of
ecoli. I have converted the file to sfq

**Comment by moneycat** [comment]
@devarajphukan  and @rammesessn  l'll check our program and its support of hadoop 2.7 soon. I guess there may be some incompatibility from YARN.
Sorry for inconvenient. I'll reply checking status ASAP.

Thank you for reporting.

**Comment by moneycat** [comment]
@devarajphukan and @rammesessn I've built a single node mode YARN 2.7.2 machine and test our program on it. It seems it works well on hadoop 2.7 (and w/ YARN). Then I have few suggestions about debugging on the second point in the followings.

#### First, my test scenario:
1. I download the simulated ecoli data from our another program: `https://github.com/ice91/CloudBrush/blob/master/data/Ec10k.sim.fastq`
2. Convert it to sfq (here I directly use shell script for converting): `cat Ec10k.sim.fastq | awk 'NR%4==1 {printf (NR-1)/4"\t"} NR%4==2 {printf "%s\t", $0} NR%4==0 {printf "%s\n", $0}' > Ec10k.sim.sfq`
3. upload it to HDFS: `hadoop fs -put Ec10k.sim.sfq Ecoli`
4. Run program: `yarn jar ReadStackCorrector.jar -in Ecoli -out Ecoli_ec -slots 1 -javaopts -Xmx1024m`
   Note: since my test machine has only 2 cores and 4GB RAM, I've set the number of reducers and its memory capacity on command line
5. It works 
   ![screenshot from 2016-03-08 15-51-01](https://cloud.githubusercontent.com/assets/69461/13595347/977df600-e545-11e5-8ac2-999b55579079.png)

#### Second, my suggestions are:
1. Our default slot and memory settings are set too high (40 reducers, each with 4GB RAM) which may cause long waiting (it there is no such large mappers/reducers capacity) or execution failed (if it reaches out of memory). Could you please follow my test steps to check if the program is working with the above settings?
2. For runtime debugging information, you can also check the following log files on your current execution folder.
   ![screenshot from 2016-03-08 15-53-28](https://cloud.githubusercontent.com/assets/69461/13595508/dfc3fa4e-e546-11e5-9a1b-c6d954a80d5b.png)

Hope these could help you for the problem.

Best,
Antony

**Comment by rammesessn** [comment]
@moneycat we are working on hadoop cluster with one namenode and two data nodes.I am not able to download the data from the location you specified but I already downloaded the sample input data from NCBI. Converted and uploaded into hdfs. followed the instruction given by you, still no change in the output

**Comment by hohorama** [comment]
緯駿，open source總會招來不少辛苦的額外工作。      建明

**Comment by rammesessn** [comment]
Hi @moneycat  i am getting this error 
![error2_9march](https://cloud.githubusercontent.com/assets/6651131/13633448/0a12716c-e615-11e5-894e-1c26150d6e67.png)

**Comment by rammesessn** [comment]
@moneycat  Thanks sir for the support given, I successfully run the program. In my setup we reduced the virtual memory conf from 1024 to 512
![c1](https://cloud.githubusercontent.com/assets/6651131/13669646/dd529afe-e6ea-11e5-9169-e57db93e6c02.png)
![c2](https://cloud.githubusercontent.com/assets/6651131/13669650/e2133a08-e6ea-11e5-93e7-642684a16634.png)

**Comment by moneycat** [comment]
@rammesessn Sorry for late replying. I'm also trying to figure out the reason of the issue. But it's nice to know you can run this program well. Congrats! We are appreciate that you use our program and feedback this issue. We would also like to remove the hard default settings of reducers and memory for users soon. Thank you.

Best.

**Comment by rammesessn** [comment]
Hi @moneycat  I am new to this domain (DNA sequencing), I am not able to understand the process explained in the research papers. I belong to computer science community. Would you please guide me to move forward to understand it.
